name: Provision EC2 via Terraform

on:
  workflow_dispatch:  # manual trigger

jobs:
  terraform-ec2:
    name: Provision EC2 Instance
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/ec2-runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: |
          terraform apply -auto-approve \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}" \
            -var="key_name=${{ secrets.KEY_PAIR_NAME }}"

      - name: Show Output
        run: terraform output
