name: Tool-Installation

on:
  push:
    branches: [ "main" ]

jobs:
  installation:
    runs-on: self-hosted # Important: Specifies your private runner
    steps:
    - uses: actions/checkout@v4

    - name: Ensure Docker is installed and running
      run: |
        chmod +x ./tool-installation-runner.sh
        ./tool-installation-runner.sh
  
